# This is CI-CD Action to deploy Flask to AWS Beanstalk

name: CI-CD-AWS
env:
  S3_NAME: "alvadim-github-bucket"
  APP_NAME: "MyFlaskApp"
  ENV_NAME: "Myflaskapp-env"
  DEPLOY_PKG_NAME: "flask_app_${{ github.sha }}.zip"
  AWS_REGION: "eu-central-1"
  
on:
  push:
    branches: 
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  CI-part:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create ZIP package
        run: zip -r ${{ env.DEPLOY_PKG_NAME }} ./ -x *.git*

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Copy deployment package to S3 bucket
        run: aws s3 cp ${{ env.DEPLOY_PKG_NAME }} s3://${{ env.S3_NAME }}
        
      - name: Print message
        run: echo "CI pipeline complited."
        
 
  CD-part:
    runs-on: ubuntu-latest
    needs: [CI-part]
    
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: ${{ env.AWS_REGION }}          
          
      - name: Create EBS application
        run: |
          aws elasticbeanstalk create-application-version \
          --application-name ${{ env.APP_NAME }} \
          --source-bundle S3Bucket="${{ env.S3_NAME }}",S3Key="${{ env.DEPLOY_PKG_NAME }}" \
          --version-label "Ver-${{ github.sha }}" \
          --description "CommitSHA-${{ github.sha }}"
          
      - name: Deploy ElasticBeanstalk version
        run: |
          aws elasticbeanstalk update-environment \ 
          --environment-name ${{ env.ENV_NAME }} \
          --version-label "Ver-${{ github.sha }}"
          
          - name: Print message
            run: echo "CD pipeline complited."
        
