# This is CI-CD Action to deploy Flask to AWS Beanstalk

name: CI-CD-AWS
env:
  S3_NAME: 	"alvadim-github-bucket"
  APP_NAME: "MyFlaskApp"
  ENV_NAME: "	Myflaskapp-env"
  DEPLOY_PKG_NAME: "flask_app_${{ github.sha }}.zip"
  AWS_REGION: "eu-central-1"
  
on:
  push:
    branches: 
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  CI-part:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create ZIP package
        run: zip -r ${{ env.DEPLOY_PKG_NAME }} ./ -x *.git*

      - name: Run a multi-line script
        run: echo " ${{ github.actor }} is learning GitHub Actions "
